<?php

namespace app\Http\Controllers\Web;


use app\Http\Controllers\Controller;
use app\Http\Requests\RoleRequest;
use app\Http\Requests\UserCreateRequest;
use app\Services\User\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Nahid\Permit\Facades\Permit;
use app\contacto;
use app\complementoPersonal;
use app\rht_ingreso;
use app\conyugue;
use app\rht_personal;
use app\hijo;
use app\plaza;
use app\habilidad;
use app\formacionacademica;
use app\experienciaProfesional;
use app\cursoTomado;
use app\cursoImpartido;
use app\investigacion;
use DB;
use Illuminate\Support\Facades\App;

class EstadisticaPerDocenteController extends Controller
{
    public function index()
    {
    	$personalTC=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->get();
    	$personalTCLic=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalTCEsp=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalTCMtr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalTCMtrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalTCDr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalTCDrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalTCDisc=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();

    	$personalTCm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->get();
    	$personalTCLicm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalTCEspm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalTCMtrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalTCMtrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalTCDrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalTCDrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalTCDiscm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "40")->orWhere("HORAS", "=", "00")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();



    	$personalMT=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->get();
    	$personalMTLic=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalMTEsp=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalMTMtr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalMTMtrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalMTDr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalMTDrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalMTDisc=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();

    	$personalMTm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->get();
    	$personalMTLicm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalMTEspm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalMTMtrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalMTMtrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalMTDrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalMTDrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalMTDiscm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "20")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();

        $personalTCT=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->get();
		$personalTCTLic=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalTCTEsp=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalTCTMtr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalTCTMtrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalTCTDr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalTCTDrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalTCTDisc=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();

        $personalTCTm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->get();

        $personalMTLicm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalMTEspm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalMTMtrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalMTMtrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalMTDrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalMTDrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalMTDiscm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", "=", "30")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();


        $personalAsig=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->get();
        $personalAsigLic=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalAsigEsp=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalAsigMtr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalAsigMtrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalAsigDr=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalAsigDrsg=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalAsigDisc=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "H")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();

        $personalAsigm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->get();

        $personalAsigLicm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Licenciatura')->get();
    	$personalAsigEspm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Especialidad')->get();
    	$personalAsigMtrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria con grado')->get();
    	$personalAsigMtrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Mtria sin grado')->get();
    	$personalAsigDrm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr con grado')->get();
    	$personalAsigDrsgm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Dr sin grado')->get();
    	$personalAsigDiscm=DB::table("rht_personal")->join("rht_complementopersonal", "rht_complementopersonal.personal", "=", "rht_personal.id")->join("rht_plaza","rht_plaza.personal","=","rht_complementopersonal.id")->join("rht_catalogoplaza", "rht_catalogoplaza.id", "=", "rht_plaza.categoria")->select("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->where("rht_personal.sexo", "=", "M")->where("HORAS", ">=", "1")->where("HORAS", "<=", "19")->groupBy("rht_personal.sexo", "rht_complementopersonal.gradoMaximo", "rht_plaza.categoria","rht_catalogoplaza.HORAS")->having('gradoMaximo', '=', 'Discapacidad')->get();
        //dd(count($personalTC),count($personalTCm),count($personalMT),count($personalMTm),count($personalTCT),count($personalTCTm),count($personalAsig),count($personalAsigm));
        $dompdf = App::make("dompdf.wrapper");
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->loadView("estadisticas.estadisticadocs.index",compact('personalTC','personalTCm','personalMT','personalMTm','personalTCT','personalTCTm','personalAsig','personalAsigm','personalTCLic','personalTCLicm','personalTCEsp','personalTCEspm','personalTCMtr','personalTCMtrm','personalTCMtrsg','personalTCMtrsgm','personalTCDr','personalTCDrm','personalTCDrsg','personalTCDrsgm','personalTCDisc','personalTCDiscm','personalMTLic','personalMTEsp','personalMTMtr','personalMTMtrsg','personalMTDr','personalMTDrsg','personalMTDisc','personalMTLicm','personalMTEspm','personalMTMtrm','personalMTMtrsgm','personalMTDrm','personalMTDrsgm','personalMTDiscm','personalTCTLic','personalTCTEsp','personalTCTMtr','personalTCTMtrsg','personalTCTDr','personalTCTDrsg','personalTCTDisc','personalMTLicm','personalMTEspm','personalMTMtrm','personalMTMtrsgm','personalMTDrm','personalMTDrsgm','personalMTDiscm','personalAsigLic','personalAsigEsp','personalAsigMtr','personalAsigMtrsg','personalAsigDr','personalAsigDrsg','personalAsigDisc','personalAsigLicm','personalAsigEspm','personalAsigMtrm','personalAsigMtrsgm','personalAsigDrm','personalAsigDrsgm','personalAsigDiscm'));
        return $dompdf->stream();
    }

    
}



    	
    
    	

